PROGRAM_NAME = "himawari8-observer"
SOFTWARE_VERSION = "v1.4.0"
DESCRIPTION = """Regularly set the images from the Himawari8 satellite as desktop wallpaper."""
WEBSITE = "https://github.com/zhengqingquan/himawari8-observer"
RELEASES_URL = f"{WEBSITE}/releases/latest"
GITHUB_API_LATEST = "https://api.github.com/repos/zhengqingquan/himawari8-observer/releases/latest"
EPILOG = f"""Github: {WEBSITE}"""
